### ISSUE TITLE
GCA (NCBI) vs EBI naming format

### ISSUE THREAD

**Issue by jjkoehorst** [enasequence/enaBrowserTools#26]
I am pretty used to use the GCA formatting in various projects as it was easier to sync via ftp at NCBI then via the EBI but with this application those problems are most likely solved.

However, is there an easy way to go from GCA > EBI/ENA formatting? I am currently playing with the taxon ids as this is the general id that is in common but not unique to single organisms... Also the identifiers (http://www.ebi.ac.uk/ena/data/view/GCA_000007565.1) do "exist" at EBI but not allowed via the retrieval application?

**Comment by nicsilvester** [comment]
You can fetch assemblies (GCA accession) using these scripts. E.g., the following will download the sequences in EMBL flat file format (without any WGS set):
```
enaDataGet GCA_000007565.1
```

Can you please let me know what commands/options you are using that is failing to fetch the assembly?

**Comment by jjkoehorst** [comment]
Just wanted to test it but

    ./enaDataGet GCA_000007565.1
    ERROR: Something unexpected went wrong please try again.
    If problem persists, please contact datasubs@ebi.ac.uk for assistance.

**Comment by nicsilvester** [comment]
Thanks.  Sorry this was a problem that had been fixed in the python2 scripts but missed in the python3 scripts. Fixed in version 1.4.1

**Comment by jjkoehorst** [comment]
Thanks for the fix, however I stumbled upon something else as well (not sure if I should open a new ticket or not)

When looking for GCA_000007565 which is _Pseudomonas putida KT2440_ if I use the 

    ./enaGroupGet -g wgs -f embl -d ../../ENA/ --wgs --meta --index --subtree 2

command I get only ENA identifiers which is ok, but I have the feeling I am then missing the "complete genomes such as KT2440" I can do a --subtree on the assembly but I really only need the EMBL file. Is there a way to have all bacterial genomes, draft/complete/others... using a single approach?

**Comment by nicsilvester** [comment]
I'm not completely sure what you mean by "get only ENA identifiers". Could you please clarify? 

If you mean that you are missing complete genomes that have not been submitted as genome assemblies (therefore have no GCA_ accession) and only as single assembled sequences, then there are some complications with this.  You can obtain all sequences in the bacterial subtree (using group sequence), but then you will get all bacterial sequences and not just sequences with "complete genome" in the description lines.

These scripts are currently meant to download sequences with known accessions, and we don't have any short term intentions to include full use of our search APIs into these scripts. We added the taxon 'search' support only because this was a common download action. For finer searches looking to narrow down the assembled sequences to what you need, for now you need to use our advanced search.

**Comment by jjkoehorst** [comment]
Ok, let me try to explain it further.

In the case of KT2440:

http://www.uniprot.org/taxonomy/160488

When using --subtree 2 -f embl -g wgs I was under the impression that this would list / obtain all bacterial genomes that are out there including KT2440 as I set no restrictions on complete or draft.

However,

    ./enaGroupGet --meta --index --subtree 160488 -f embl -g wgs
    Completed

creating a folder 160488 with no files

But when running

    ./enaGroupGet --meta --index --subtree 160488 -f embl -g assembly

it receives:

    Fetching GCA_000007565
    Completed

Thus to me this indicates that the complete genomes are most likely not present in `-g wgs`?
And if this is the case how can I then reliably receive the embl file with the sequence(s)? As for comparative studies missing complete genomes can have a big impact.

**Comment by nicsilvester** [comment]
You can download the following:

-g wgs: downloads only WGS sets

-g assembly: downloads only genome assemblies (submitted as a genome assembly, with GCA accession for the assembly, most if not all WGS sets will be included in this group)

-g sequence: downloads assembled and annotated sequences, both those that have been submitted as part of an assembly and those that have not.

To do a finer search against the sequence group, you will need to use our search services rather than these download tools.

This now seems to be the same topic as the open issue #29, please continue any correspondence on the open issue.
