### ISSUE TITLE
Fetching genomes sometimes get stuck

### ISSUE THREAD

**Issue by jjkoehorst** [enasequence/enaBrowserTools#35]
I have been trying the following command (on a Mac):

`python3 enaBrowserTools/python3/enaDataGet.py -f embl GCA_000393655.1`

and notices that it gets stuck on unplaced-scaffold and not sure how to continue.

```
no sequences: assembled-molecule
no sequences: unlocalised-scaffold
fetching sequences: unplaced-scaffold
```

The folder content:

```
-rw-r--r--  1 me  staff   4.5K May  9 16:51 GCA_000393655.1.xml
-rw-r--r--  1 me  staff    19M May  9 16:51 GCA_000393655.1_sequence_report.txt
-rw-r--r--  1 me  staff     0B May  9 16:51 unplaced-scaffold.dat
```

**Update**

On our ubuntu server it obtains the data but very slowly and shows a lot of:

`Entry: ASAF01227205 display type is either not supported or entry is not found.`

**Update 2**

As shown on the main page of this git project it indeed states to fix the certificates.

However as I used home-brew to install python3 I needed the following code to run:

```
# install_certifi.py
#
# sample script to install or update a set of default Root Certificates
# for the ssl module.  Uses the certificates provided by the certifi package:
#       https://pypi.python.org/pypi/certifi

import os
import os.path
import ssl
import stat
import subprocess
import sys

STAT_0o775 = ( stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR
             | stat.S_IRGRP | stat.S_IWGRP | stat.S_IXGRP
             | stat.S_IROTH |                stat.S_IXOTH )

openssl_dir, openssl_cafile = os.path.split(
    ssl.get_default_verify_paths().openssl_cafile)

print(" -- pip install --upgrade certifi")
subprocess.check_call([sys.executable,
    "-E", "-s", "-m", "pip", "install", "--upgrade", "certifi"])

import certifi

# change working directory to the default SSL directory
os.chdir(openssl_dir)
relpath_to_certifi_cafile = os.path.relpath(certifi.where())
print(" -- removing any existing file or link")
try:
    os.remove(openssl_cafile)
except FileNotFoundError:
    pass
print(" -- creating symlink to certifi certificate bundle")
os.symlink(relpath_to_certifi_cafile, openssl_cafile)
print(" -- setting permissions")
os.chmod(openssl_cafile, STAT_0o775)
print(" -- update complete")
```

but it is not yet 100% fixed. Not sure why some genomes do work while others don't.

**Comment by nicsilvester** [comment]
Thanks, I'll have a look. The new update should have removed the check for the WGS sequences which should make a significant difference. Genomes with large numbers of WGS scaffolds were (before the update) having more difficulty with download as you have shown (with the Entry: ... message).
I'll double check that the update was made as expected in the python 3 scripts and not just the python 2 ones. A copy may have been missed and I may have just gotten lucky with the tests. Please look at the release notes for the latest release to see what the new solution for WGS scaffolds is (this is required, in part, to address the change in the ENA browser where individual WGS sequences are no longer retrievable).

Thanks also for the info on what you needed to do to sort out the certificate problem. I'll look at updating the documentation. Unfortunately this problem came as an unpleasant surprise when running the tests ready to release the update and realising the EBI move to HTTPS caused a problem with many Mac Python3 installations.

**Comment by nicsilvester** [comment]
Found the problem. Had accidentally removed the binary part of the write and a check. Have the fix ready to deploy. Before I do though, a follow up question...
In the assembly example you gave there are CON records. When you fetch the embl format, you don't get the sequence for these, just the information on how the record is constructed. In contrast, when you fetch the fasta format, you will get the constructed sequence. This is a default of our browser but there is a way to ask for the full constructed sequence to be contained within the flat file. Would you want the constructed sequence? And if so, by default or using a flag?

**Comment by jjkoehorst** [comment]
Great to hear! I am using python3 as much as possible due to the end of life (in a while).

When fetching the EMBL format I personally would like to get as much information as possible thus indeed the sequence. With the constructed you also mean the "joins" at the end of an embl file? It would be very nice when retrieving the EMBL file it is as complete as possible, preferably by default but an additional option is fine to.

**Comment by jjkoehorst** [comment]
I just pulled in the latest master branch and it seems to be working perfect. If I encounter any strange behaviour I will let you know.

**Comment by jjkoehorst** [comment]
Not sure if is related to this topic but of today I noticed a severe descries in download speed ±20kb/s.
This happens when it is downloading the unplaced-scaffold.dat file.

**Comment by nicsilvester** [comment]
Sorry. I missed the notification for this when you posted it. Just seen it this week. The unplaced scaffolds step will go through the sequence report and check if any of the scaffolds listed are in the WGS set. It also needs to check and download any sequences that are not and then download the WGS set if there were any WGS scaffolds. If it turns out that all of the unplaced scaffolds are in the WGS set, then this step is redundant, but there is no way for it to know this without scanning the full file. This is an unfortunate side effect of scaffolds being added to WGS sets a few years ago. When they only held contigs, life was simpler :)
I'll check the code to see if there is a way to simplify and speed up this step.

**Comment by nicsilvester** [comment]
I've updated the code (getting released later today) to use the new browser API which should speed things up. However the problem is where there is a very large number of unplaced scaffolds. In the example above there are over 36000 unplaced scaffolds that are not WGS sequences. I think the time is being largely taken with the individual fetch of sequences (over 36000 URL calls). I'll contact my former colleagues at ENA with a feature request that the new API can take a list of sequences (e.g. read in by file) so that there is a single URL call. Or perhaps better would be several calls capping the list of sequences at 1000 at a time. 37 URL calls is still much better than >3600 :)
