### ISSUE TITLE
ensDataGet for entity with absent default files gives random binary output

### ISSUE THREAD

**Issue by swingingsimian** [enasequence/enaBrowserTools#39]
Doing a search for a Run (I think the default download for Run is submitted files), which has no submitted files gives odd output:

```
$ enaDataGet -as ./aspera_settings.ini SRR6682864
Downloading file with md5 check:ftp.sra.ebi.ac.uk/vol1/srr/SRR668/004/SRR6682864
$ tree SRR6682864
SRR6682864
└── SRR6682864

0 directories, 1 file
$ more SRR6682864/SRR6682864
"SRR6682864/SRR6682864" may be a binary file.  See it anyway?
$ enaDataGet -as ./aspera_settings.ini -f fastq SRR6682864
Downloading file with md5 check:ftp.sra.ebi.ac.uk/vol1/fastq/SRR668/004/SRR6682864/SRR6682864_1.fastq.gz
Downloading file with md5 check:ftp.sra.ebi.ac.uk/vol1/fastq/SRR668/004/SRR6682864/SRR6682864_2.fastq.gz
```
Thanks

**Comment by nicsilvester** [comment]
When there are no submitted files, it should download the FASTQ (or potentially the SRA files if NCBI/DDBJ source runs, I need to double check the decided logic). I'm not sure if this is already released or in the update that is yet to be released. I'll look into it and make sure the new update is acting as expected.

**Comment by nicsilvester** [comment]
Have looked into this some more and can confirm that the logic to download a run when not stating the format is:
- If the run was submitted to ENA (ERR): first look for the submitted file, if not available, download the FASTQ
- If the run was submitted to DDBJ (DRR) or NCBI (SRR): first look for the SRA file (this is the file ENA gets as part of the data mirror process), if not available, download the FASTQ

In most cases the FASTQ should not be downloaded. If it is, one of two things may be true:
1. The submitted version was FASTQ
2. There is a problem with the submitted file (if you want it instead of FASTQ you should contact ENA)

In your example above, in your first download you have downloaded the SRA file, which is a single binary file. There is a hint here with the message: "SRR6682864/SRR6682864" may be a binary file.  See it anyway?
In your second download you have explicitly asked for the FASTQ format, which results in the paired files.
